/*
 * generated by Xtext 2.23.0
 */
package fr.n7.ui.tests;

import com.google.inject.Injector;
import fr.n7.csvToTable.ui.internal.CsvToTableActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class CSVToTableUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CsvToTableActivator.getInstance().getInjector("fr.n7.CSVToTable");
	}

}
