/**
 * generated by Xtext 2.23.0
 */
package fr.n7.algorithmeXtext;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fr.n7.algorithmeXtext.AlgorithmeXtextFactory
 * @model kind="package"
 * @generated
 */
public interface AlgorithmeXtextPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "algorithmeXtext";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.n7.fr/AlgorithmeXtext";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "algorithmeXtext";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AlgorithmeXtextPackage eINSTANCE = fr.n7.algorithmeXtext.impl.AlgorithmeXtextPackageImpl.init();

  /**
   * The meta object id for the '{@link fr.n7.algorithmeXtext.impl.AlgorithmeImpl <em>Algorithme</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.algorithmeXtext.impl.AlgorithmeImpl
   * @see fr.n7.algorithmeXtext.impl.AlgorithmeXtextPackageImpl#getAlgorithme()
   * @generated
   */
  int ALGORITHME = 0;

  /**
   * The feature id for the '<em><b>Nom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHME__NOM = 0;

  /**
   * The feature id for the '<em><b>Algorithme Element</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHME__ALGORITHME_ELEMENT = 1;

  /**
   * The number of structural features of the '<em>Algorithme</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHME_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.n7.algorithmeXtext.impl.AlgorithmeElementImpl <em>Algorithme Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.algorithmeXtext.impl.AlgorithmeElementImpl
   * @see fr.n7.algorithmeXtext.impl.AlgorithmeXtextPackageImpl#getAlgorithmeElement()
   * @generated
   */
  int ALGORITHME_ELEMENT = 1;

  /**
   * The feature id for the '<em><b>Nom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHME_ELEMENT__NOM = 0;

  /**
   * The number of structural features of the '<em>Algorithme Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHME_ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.n7.algorithmeXtext.impl.RessourceImpl <em>Ressource</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.algorithmeXtext.impl.RessourceImpl
   * @see fr.n7.algorithmeXtext.impl.AlgorithmeXtextPackageImpl#getRessource()
   * @generated
   */
  int RESSOURCE = 2;

  /**
   * The feature id for the '<em><b>Nom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESSOURCE__NOM = ALGORITHME_ELEMENT__NOM;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESSOURCE__TYPE = ALGORITHME_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Ressource</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESSOURCE_FEATURE_COUNT = ALGORITHME_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.n7.algorithmeXtext.impl.SortieImpl <em>Sortie</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.algorithmeXtext.impl.SortieImpl
   * @see fr.n7.algorithmeXtext.impl.AlgorithmeXtextPackageImpl#getSortie()
   * @generated
   */
  int SORTIE = 3;

  /**
   * The feature id for the '<em><b>Nom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SORTIE__NOM = ALGORITHME_ELEMENT__NOM;

  /**
   * The feature id for the '<em><b>Valeur</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SORTIE__VALEUR = ALGORITHME_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Sortie</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SORTIE_FEATURE_COUNT = ALGORITHME_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.n7.algorithmeXtext.impl.EntreeImpl <em>Entree</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.algorithmeXtext.impl.EntreeImpl
   * @see fr.n7.algorithmeXtext.impl.AlgorithmeXtextPackageImpl#getEntree()
   * @generated
   */
  int ENTREE = 4;

  /**
   * The feature id for the '<em><b>Nom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTREE__NOM = ALGORITHME_ELEMENT__NOM;

  /**
   * The feature id for the '<em><b>Argument</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTREE__ARGUMENT = ALGORITHME_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Entree</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTREE_FEATURE_COUNT = ALGORITHME_ELEMENT_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link fr.n7.algorithmeXtext.Algorithme <em>Algorithme</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Algorithme</em>'.
   * @see fr.n7.algorithmeXtext.Algorithme
   * @generated
   */
  EClass getAlgorithme();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.algorithmeXtext.Algorithme#getNom <em>Nom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nom</em>'.
   * @see fr.n7.algorithmeXtext.Algorithme#getNom()
   * @see #getAlgorithme()
   * @generated
   */
  EAttribute getAlgorithme_Nom();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.algorithmeXtext.Algorithme#getAlgorithmeElement <em>Algorithme Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Algorithme Element</em>'.
   * @see fr.n7.algorithmeXtext.Algorithme#getAlgorithmeElement()
   * @see #getAlgorithme()
   * @generated
   */
  EReference getAlgorithme_AlgorithmeElement();

  /**
   * Returns the meta object for class '{@link fr.n7.algorithmeXtext.AlgorithmeElement <em>Algorithme Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Algorithme Element</em>'.
   * @see fr.n7.algorithmeXtext.AlgorithmeElement
   * @generated
   */
  EClass getAlgorithmeElement();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.algorithmeXtext.AlgorithmeElement#getNom <em>Nom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nom</em>'.
   * @see fr.n7.algorithmeXtext.AlgorithmeElement#getNom()
   * @see #getAlgorithmeElement()
   * @generated
   */
  EAttribute getAlgorithmeElement_Nom();

  /**
   * Returns the meta object for class '{@link fr.n7.algorithmeXtext.Ressource <em>Ressource</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ressource</em>'.
   * @see fr.n7.algorithmeXtext.Ressource
   * @generated
   */
  EClass getRessource();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.algorithmeXtext.Ressource#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see fr.n7.algorithmeXtext.Ressource#getType()
   * @see #getRessource()
   * @generated
   */
  EAttribute getRessource_Type();

  /**
   * Returns the meta object for class '{@link fr.n7.algorithmeXtext.Sortie <em>Sortie</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sortie</em>'.
   * @see fr.n7.algorithmeXtext.Sortie
   * @generated
   */
  EClass getSortie();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.algorithmeXtext.Sortie#getValeur <em>Valeur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Valeur</em>'.
   * @see fr.n7.algorithmeXtext.Sortie#getValeur()
   * @see #getSortie()
   * @generated
   */
  EAttribute getSortie_Valeur();

  /**
   * Returns the meta object for class '{@link fr.n7.algorithmeXtext.Entree <em>Entree</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entree</em>'.
   * @see fr.n7.algorithmeXtext.Entree
   * @generated
   */
  EClass getEntree();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.algorithmeXtext.Entree#getArgument <em>Argument</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Argument</em>'.
   * @see fr.n7.algorithmeXtext.Entree#getArgument()
   * @see #getEntree()
   * @generated
   */
  EAttribute getEntree_Argument();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  AlgorithmeXtextFactory getAlgorithmeXtextFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link fr.n7.algorithmeXtext.impl.AlgorithmeImpl <em>Algorithme</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.algorithmeXtext.impl.AlgorithmeImpl
     * @see fr.n7.algorithmeXtext.impl.AlgorithmeXtextPackageImpl#getAlgorithme()
     * @generated
     */
    EClass ALGORITHME = eINSTANCE.getAlgorithme();

    /**
     * The meta object literal for the '<em><b>Nom</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALGORITHME__NOM = eINSTANCE.getAlgorithme_Nom();

    /**
     * The meta object literal for the '<em><b>Algorithme Element</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALGORITHME__ALGORITHME_ELEMENT = eINSTANCE.getAlgorithme_AlgorithmeElement();

    /**
     * The meta object literal for the '{@link fr.n7.algorithmeXtext.impl.AlgorithmeElementImpl <em>Algorithme Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.algorithmeXtext.impl.AlgorithmeElementImpl
     * @see fr.n7.algorithmeXtext.impl.AlgorithmeXtextPackageImpl#getAlgorithmeElement()
     * @generated
     */
    EClass ALGORITHME_ELEMENT = eINSTANCE.getAlgorithmeElement();

    /**
     * The meta object literal for the '<em><b>Nom</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALGORITHME_ELEMENT__NOM = eINSTANCE.getAlgorithmeElement_Nom();

    /**
     * The meta object literal for the '{@link fr.n7.algorithmeXtext.impl.RessourceImpl <em>Ressource</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.algorithmeXtext.impl.RessourceImpl
     * @see fr.n7.algorithmeXtext.impl.AlgorithmeXtextPackageImpl#getRessource()
     * @generated
     */
    EClass RESSOURCE = eINSTANCE.getRessource();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RESSOURCE__TYPE = eINSTANCE.getRessource_Type();

    /**
     * The meta object literal for the '{@link fr.n7.algorithmeXtext.impl.SortieImpl <em>Sortie</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.algorithmeXtext.impl.SortieImpl
     * @see fr.n7.algorithmeXtext.impl.AlgorithmeXtextPackageImpl#getSortie()
     * @generated
     */
    EClass SORTIE = eINSTANCE.getSortie();

    /**
     * The meta object literal for the '<em><b>Valeur</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SORTIE__VALEUR = eINSTANCE.getSortie_Valeur();

    /**
     * The meta object literal for the '{@link fr.n7.algorithmeXtext.impl.EntreeImpl <em>Entree</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.algorithmeXtext.impl.EntreeImpl
     * @see fr.n7.algorithmeXtext.impl.AlgorithmeXtextPackageImpl#getEntree()
     * @generated
     */
    EClass ENTREE = eINSTANCE.getEntree();

    /**
     * The meta object literal for the '<em><b>Argument</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTREE__ARGUMENT = eINSTANCE.getEntree_Argument();

  }

} //AlgorithmeXtextPackage
