/**
 * generated by Xtext 2.23.0
 */
package fr.n7.algorithmeXtext;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see fr.n7.algorithmeXtext.AlgorithmeXtextPackage
 * @generated
 */
public interface AlgorithmeXtextFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AlgorithmeXtextFactory eINSTANCE = fr.n7.algorithmeXtext.impl.AlgorithmeXtextFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Algorithme</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Algorithme</em>'.
   * @generated
   */
  Algorithme createAlgorithme();

  /**
   * Returns a new object of class '<em>Algorithme Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Algorithme Element</em>'.
   * @generated
   */
  AlgorithmeElement createAlgorithmeElement();

  /**
   * Returns a new object of class '<em>Ressource</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ressource</em>'.
   * @generated
   */
  Ressource createRessource();

  /**
   * Returns a new object of class '<em>Sortie</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sortie</em>'.
   * @generated
   */
  Sortie createSortie();

  /**
   * Returns a new object of class '<em>Entree</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entree</em>'.
   * @generated
   */
  Entree createEntree();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  AlgorithmeXtextPackage getAlgorithmeXtextPackage();

} //AlgorithmeXtextFactory
