/**
 * generated by Xtext 2.23.0
 */
package fr.n7.algorithmeXtext;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entree</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.algorithmeXtext.Entree#getArgument <em>Argument</em>}</li>
 * </ul>
 *
 * @see fr.n7.algorithmeXtext.AlgorithmeXtextPackage#getEntree()
 * @model
 * @generated
 */
public interface Entree extends AlgorithmeElement
{
  /**
   * Returns the value of the '<em><b>Argument</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Argument</em>' attribute.
   * @see #setArgument(String)
   * @see fr.n7.algorithmeXtext.AlgorithmeXtextPackage#getEntree_Argument()
   * @model
   * @generated
   */
  String getArgument();

  /**
   * Sets the value of the '{@link fr.n7.algorithmeXtext.Entree#getArgument <em>Argument</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Argument</em>' attribute.
   * @see #getArgument()
   * @generated
   */
  void setArgument(String value);

} // Entree
