/**
 * generated by Xtext 2.23.0
 */
package fr.n7.algorithmeXtext;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ressource</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.algorithmeXtext.Ressource#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see fr.n7.algorithmeXtext.AlgorithmeXtextPackage#getRessource()
 * @model
 * @generated
 */
public interface Ressource extends AlgorithmeElement
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see fr.n7.algorithmeXtext.AlgorithmeXtextPackage#getRessource_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link fr.n7.algorithmeXtext.Ressource#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

} // Ressource
