/**
 * generated by Xtext 2.23.0
 */
package fr.n7.algorithmeXtext;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sortie</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.algorithmeXtext.Sortie#getValeur <em>Valeur</em>}</li>
 * </ul>
 *
 * @see fr.n7.algorithmeXtext.AlgorithmeXtextPackage#getSortie()
 * @model
 * @generated
 */
public interface Sortie extends AlgorithmeElement
{
  /**
   * Returns the value of the '<em><b>Valeur</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Valeur</em>' attribute.
   * @see #setValeur(String)
   * @see fr.n7.algorithmeXtext.AlgorithmeXtextPackage#getSortie_Valeur()
   * @model
   * @generated
   */
  String getValeur();

  /**
   * Sets the value of the '{@link fr.n7.algorithmeXtext.Sortie#getValeur <em>Valeur</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Valeur</em>' attribute.
   * @see #getValeur()
   * @generated
   */
  void setValeur(String value);

} // Sortie
