/*
 * generated by Xtext 2.23.0
 */
package fr.n7.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.n7.AlgorithmeXtextRuntimeModule;
import fr.n7.AlgorithmeXtextStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class AlgorithmeXtextIdeSetup extends AlgorithmeXtextStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new AlgorithmeXtextRuntimeModule(), new AlgorithmeXtextIdeModule()));
	}
	
}
