/*
 * generated by Xtext 2.23.0
 */
package fr.n7.serializer;

import com.google.inject.Inject;
import fr.n7.algorithmeXtext.Algorithme;
import fr.n7.algorithmeXtext.AlgorithmeXtextPackage;
import fr.n7.algorithmeXtext.Entree;
import fr.n7.algorithmeXtext.Ressource;
import fr.n7.algorithmeXtext.Sortie;
import fr.n7.services.AlgorithmeXtextGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class AlgorithmeXtextSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private AlgorithmeXtextGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == AlgorithmeXtextPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case AlgorithmeXtextPackage.ALGORITHME:
				sequence_Algorithme(context, (Algorithme) semanticObject); 
				return; 
			case AlgorithmeXtextPackage.ENTREE:
				sequence_Entree(context, (Entree) semanticObject); 
				return; 
			case AlgorithmeXtextPackage.RESSOURCE:
				sequence_Ressource(context, (Ressource) semanticObject); 
				return; 
			case AlgorithmeXtextPackage.SORTIE:
				sequence_Sortie(context, (Sortie) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Algorithme returns Algorithme
	 *
	 * Constraint:
	 *     (nom=Nom algorithmeElement+=AlgorithmeElement+)
	 */
	protected void sequence_Algorithme(ISerializationContext context, Algorithme semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     AlgorithmeElement returns Entree
	 *     Entree returns Entree
	 *
	 * Constraint:
	 *     (nom=Nom argument=Argument)
	 */
	protected void sequence_Entree(ISerializationContext context, Entree semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, AlgorithmeXtextPackage.Literals.ALGORITHME_ELEMENT__NOM) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AlgorithmeXtextPackage.Literals.ALGORITHME_ELEMENT__NOM));
			if (transientValues.isValueTransient(semanticObject, AlgorithmeXtextPackage.Literals.ENTREE__ARGUMENT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AlgorithmeXtextPackage.Literals.ENTREE__ARGUMENT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEntreeAccess().getNomNomParserRuleCall_1_0(), semanticObject.getNom());
		feeder.accept(grammarAccess.getEntreeAccess().getArgumentArgumentParserRuleCall_3_0(), semanticObject.getArgument());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     AlgorithmeElement returns Ressource
	 *     Ressource returns Ressource
	 *
	 * Constraint:
	 *     (nom=Chemin type=TypeAlgo)
	 */
	protected void sequence_Ressource(ISerializationContext context, Ressource semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, AlgorithmeXtextPackage.Literals.ALGORITHME_ELEMENT__NOM) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AlgorithmeXtextPackage.Literals.ALGORITHME_ELEMENT__NOM));
			if (transientValues.isValueTransient(semanticObject, AlgorithmeXtextPackage.Literals.RESSOURCE__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AlgorithmeXtextPackage.Literals.RESSOURCE__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRessourceAccess().getNomCheminParserRuleCall_1_0(), semanticObject.getNom());
		feeder.accept(grammarAccess.getRessourceAccess().getTypeTypeAlgoParserRuleCall_3_0(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     AlgorithmeElement returns Sortie
	 *     Sortie returns Sortie
	 *
	 * Constraint:
	 *     (nom=Nom valeur=Resultat?)
	 */
	protected void sequence_Sortie(ISerializationContext context, Sortie semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
