/*
 * generated by Xtext 2.23.0
 */
package fr.n7.parser.antlr;

import com.google.inject.Inject;
import fr.n7.parser.antlr.internal.InternalCSVToTableParser;
import fr.n7.services.CSVToTableGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class CSVToTableParser extends AbstractAntlrParser {

	@Inject
	private CSVToTableGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCSVToTableParser createParser(XtextTokenStream stream) {
		return new InternalCSVToTableParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Tableau";
	}

	public CSVToTableGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CSVToTableGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
