/**
 * generated by Xtext 2.23.0
 */
package fr.n7.cSVToTable;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see fr.n7.cSVToTable.CSVToTablePackage
 * @generated
 */
public interface CSVToTableFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CSVToTableFactory eINSTANCE = fr.n7.cSVToTable.impl.CSVToTableFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Tableau</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tableau</em>'.
   * @generated
   */
  Tableau createTableau();

  /**
   * Returns a new object of class '<em>Ligne Nom</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ligne Nom</em>'.
   * @generated
   */
  LigneNom createLigneNom();

  /**
   * Returns a new object of class '<em>Colonne ID</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Colonne ID</em>'.
   * @generated
   */
  ColonneID createColonneID();

  /**
   * Returns a new object of class '<em>Ligne Valeur</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ligne Valeur</em>'.
   * @generated
   */
  LigneValeur createLigneValeur();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  CSVToTablePackage getCSVToTablePackage();

} //CSVToTableFactory
