/**
 * generated by Xtext 2.23.0
 */
package fr.n7.cSVToTable;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fr.n7.cSVToTable.CSVToTableFactory
 * @model kind="package"
 * @generated
 */
public interface CSVToTablePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "cSVToTable";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.n7.fr/CSVToTable";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "cSVToTable";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CSVToTablePackage eINSTANCE = fr.n7.cSVToTable.impl.CSVToTablePackageImpl.init();

  /**
   * The meta object id for the '{@link fr.n7.cSVToTable.impl.TableauImpl <em>Tableau</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.cSVToTable.impl.TableauImpl
   * @see fr.n7.cSVToTable.impl.CSVToTablePackageImpl#getTableau()
   * @generated
   */
  int TABLEAU = 0;

  /**
   * The number of structural features of the '<em>Tableau</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLEAU_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.n7.cSVToTable.impl.LigneNomImpl <em>Ligne Nom</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.cSVToTable.impl.LigneNomImpl
   * @see fr.n7.cSVToTable.impl.CSVToTablePackageImpl#getLigneNom()
   * @generated
   */
  int LIGNE_NOM = 1;

  /**
   * The feature id for the '<em><b>Lines</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIGNE_NOM__LINES = TABLEAU_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Ligne Nom</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIGNE_NOM_FEATURE_COUNT = TABLEAU_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.n7.cSVToTable.impl.ColonneIDImpl <em>Colonne ID</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.cSVToTable.impl.ColonneIDImpl
   * @see fr.n7.cSVToTable.impl.CSVToTablePackageImpl#getColonneID()
   * @generated
   */
  int COLONNE_ID = 2;

  /**
   * The feature id for the '<em><b>Lines</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE_ID__LINES = LIGNE_NOM__LINES;

  /**
   * The feature id for the '<em><b>Colonnes</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE_ID__COLONNES = LIGNE_NOM_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Nom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE_ID__NOM = LIGNE_NOM_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Colonne ID</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLONNE_ID_FEATURE_COUNT = LIGNE_NOM_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.n7.cSVToTable.impl.LigneValeurImpl <em>Ligne Valeur</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.cSVToTable.impl.LigneValeurImpl
   * @see fr.n7.cSVToTable.impl.CSVToTablePackageImpl#getLigneValeur()
   * @generated
   */
  int LIGNE_VALEUR = 3;

  /**
   * The feature id for the '<em><b>Valeurs</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIGNE_VALEUR__VALEURS = 0;

  /**
   * The number of structural features of the '<em>Ligne Valeur</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIGNE_VALEUR_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link fr.n7.cSVToTable.Tableau <em>Tableau</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tableau</em>'.
   * @see fr.n7.cSVToTable.Tableau
   * @generated
   */
  EClass getTableau();

  /**
   * Returns the meta object for class '{@link fr.n7.cSVToTable.LigneNom <em>Ligne Nom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ligne Nom</em>'.
   * @see fr.n7.cSVToTable.LigneNom
   * @generated
   */
  EClass getLigneNom();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.cSVToTable.LigneNom#getLines <em>Lines</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Lines</em>'.
   * @see fr.n7.cSVToTable.LigneNom#getLines()
   * @see #getLigneNom()
   * @generated
   */
  EReference getLigneNom_Lines();

  /**
   * Returns the meta object for class '{@link fr.n7.cSVToTable.ColonneID <em>Colonne ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Colonne ID</em>'.
   * @see fr.n7.cSVToTable.ColonneID
   * @generated
   */
  EClass getColonneID();

  /**
   * Returns the meta object for the attribute list '{@link fr.n7.cSVToTable.ColonneID#getColonnes <em>Colonnes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Colonnes</em>'.
   * @see fr.n7.cSVToTable.ColonneID#getColonnes()
   * @see #getColonneID()
   * @generated
   */
  EAttribute getColonneID_Colonnes();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.cSVToTable.ColonneID#getNom <em>Nom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nom</em>'.
   * @see fr.n7.cSVToTable.ColonneID#getNom()
   * @see #getColonneID()
   * @generated
   */
  EAttribute getColonneID_Nom();

  /**
   * Returns the meta object for class '{@link fr.n7.cSVToTable.LigneValeur <em>Ligne Valeur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ligne Valeur</em>'.
   * @see fr.n7.cSVToTable.LigneValeur
   * @generated
   */
  EClass getLigneValeur();

  /**
   * Returns the meta object for the attribute list '{@link fr.n7.cSVToTable.LigneValeur#getValeurs <em>Valeurs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Valeurs</em>'.
   * @see fr.n7.cSVToTable.LigneValeur#getValeurs()
   * @see #getLigneValeur()
   * @generated
   */
  EAttribute getLigneValeur_Valeurs();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  CSVToTableFactory getCSVToTableFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link fr.n7.cSVToTable.impl.TableauImpl <em>Tableau</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.cSVToTable.impl.TableauImpl
     * @see fr.n7.cSVToTable.impl.CSVToTablePackageImpl#getTableau()
     * @generated
     */
    EClass TABLEAU = eINSTANCE.getTableau();

    /**
     * The meta object literal for the '{@link fr.n7.cSVToTable.impl.LigneNomImpl <em>Ligne Nom</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.cSVToTable.impl.LigneNomImpl
     * @see fr.n7.cSVToTable.impl.CSVToTablePackageImpl#getLigneNom()
     * @generated
     */
    EClass LIGNE_NOM = eINSTANCE.getLigneNom();

    /**
     * The meta object literal for the '<em><b>Lines</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIGNE_NOM__LINES = eINSTANCE.getLigneNom_Lines();

    /**
     * The meta object literal for the '{@link fr.n7.cSVToTable.impl.ColonneIDImpl <em>Colonne ID</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.cSVToTable.impl.ColonneIDImpl
     * @see fr.n7.cSVToTable.impl.CSVToTablePackageImpl#getColonneID()
     * @generated
     */
    EClass COLONNE_ID = eINSTANCE.getColonneID();

    /**
     * The meta object literal for the '<em><b>Colonnes</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLONNE_ID__COLONNES = eINSTANCE.getColonneID_Colonnes();

    /**
     * The meta object literal for the '<em><b>Nom</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLONNE_ID__NOM = eINSTANCE.getColonneID_Nom();

    /**
     * The meta object literal for the '{@link fr.n7.cSVToTable.impl.LigneValeurImpl <em>Ligne Valeur</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.cSVToTable.impl.LigneValeurImpl
     * @see fr.n7.cSVToTable.impl.CSVToTablePackageImpl#getLigneValeur()
     * @generated
     */
    EClass LIGNE_VALEUR = eINSTANCE.getLigneValeur();

    /**
     * The meta object literal for the '<em><b>Valeurs</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LIGNE_VALEUR__VALEURS = eINSTANCE.getLigneValeur_Valeurs();

  }

} //CSVToTablePackage
