/**
 * generated by Xtext 2.23.0
 */
package fr.n7.cSVToTable;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ligne Nom</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.cSVToTable.LigneNom#getLines <em>Lines</em>}</li>
 *   <li>{@link fr.n7.cSVToTable.LigneNom#getColonnes <em>Colonnes</em>}</li>
 * </ul>
 *
 * @see fr.n7.cSVToTable.CSVToTablePackage#getLigneNom()
 * @model
 * @generated
 */
public interface LigneNom extends Tableau
{
  /**
   * Returns the value of the '<em><b>Lines</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.cSVToTable.LigneValeur}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lines</em>' containment reference list.
   * @see fr.n7.cSVToTable.CSVToTablePackage#getLigneNom_Lines()
   * @model containment="true"
   * @generated
   */
  EList<LigneValeur> getLines();

  /**
   * Returns the value of the '<em><b>Colonnes</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Colonnes</em>' attribute list.
   * @see fr.n7.cSVToTable.CSVToTablePackage#getLigneNom_Colonnes()
   * @model unique="false"
   * @generated
   */
  EList<String> getColonnes();

} // LigneNom
