/**
 * generated by Xtext 2.23.0
 */
package fr.n7.cSVToTable;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Tableau</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.n7.cSVToTable.CSVToTablePackage#getTableau()
 * @model
 * @generated
 */
public interface Tableau extends EObject
{
} // Tableau
