/*
 * generated by Xtext 2.23.0
 */
package fr.n7;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class AlgorithmeXtextStandaloneSetup extends AlgorithmeXtextStandaloneSetupGenerated {

	public static void doSetup() {
		new AlgorithmeXtextStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
