/**
 * generated by Xtext 2.23.0
 */
package fr.n7.cSVToTable.impl;

import fr.n7.cSVToTable.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class CSVToTableFactoryImpl extends EFactoryImpl implements CSVToTableFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static CSVToTableFactory init()
  {
    try
    {
      CSVToTableFactory theCSVToTableFactory = (CSVToTableFactory)EPackage.Registry.INSTANCE.getEFactory(CSVToTablePackage.eNS_URI);
      if (theCSVToTableFactory != null)
      {
        return theCSVToTableFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new CSVToTableFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CSVToTableFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case CSVToTablePackage.TABLEAU: return createTableau();
      case CSVToTablePackage.LIGNE_NOM: return createLigneNom();
      case CSVToTablePackage.COLONNE_ID: return createColonneID();
      case CSVToTablePackage.LIGNE_VALEUR: return createLigneValeur();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Tableau createTableau()
  {
    TableauImpl tableau = new TableauImpl();
    return tableau;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LigneNom createLigneNom()
  {
    LigneNomImpl ligneNom = new LigneNomImpl();
    return ligneNom;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ColonneID createColonneID()
  {
    ColonneIDImpl colonneID = new ColonneIDImpl();
    return colonneID;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LigneValeur createLigneValeur()
  {
    LigneValeurImpl ligneValeur = new LigneValeurImpl();
    return ligneValeur;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CSVToTablePackage getCSVToTablePackage()
  {
    return (CSVToTablePackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static CSVToTablePackage getPackage()
  {
    return CSVToTablePackage.eINSTANCE;
  }

} //CSVToTableFactoryImpl
