/**
 * generated by Xtext 2.23.0
 */
package fr.n7.cSVToTable.impl;

import fr.n7.cSVToTable.CSVToTablePackage;
import fr.n7.cSVToTable.Tableau;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Tableau</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TableauImpl extends MinimalEObjectImpl.Container implements Tableau
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TableauImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CSVToTablePackage.Literals.TABLEAU;
  }

} //TableauImpl
